# Creation of array

In [3]:
import numpy as np

In [4]:
np.array([10,20,30,40,50])

array([10, 20, 30, 40, 50])

In [5]:
a = [10,20,30,40,50]
np.array(a)

array([10, 20, 30, 40, 50])

# 1. It supports indexing + slicing

In [7]:
arr = np.array(a)

In [8]:
arr

array([10, 20, 30, 40, 50])

In [9]:
arr[0]        #using positive indexing

10

In [ ]:
# arr[-1]    #using negative indexing

# slicing

In [11]:
arr[2::]

array([30, 40, 50])

In [12]:
arr[::-1]

array([50, 40, 30, 20, 10])

# 3. its mutable

In [13]:
arr

array([10, 20, 30, 40, 50])

In [14]:
id(arr)

1760322442512

In [19]:
#change 10 to 100
arr[0] = 100

In [20]:
arr

array([100, 100,  30,  40,  50])

In [17]:
arr[1]=100

In [18]:
arr

array([ 10, 100,  30,  40,  50])

In [21]:
id(arr)

1760322442512

# supports Homogeneous and heterogeneous

In [23]:
arr

array([100, 100,  30,  40,  50])

In [26]:
np.array([10,'20'])

array(['10', '20'], dtype='<U11')

In [27]:
b = np.array([10,'20'])

In [28]:
b     ##it converts the data into string type as implicit type casting

array(['10', '20'], dtype='<U11')

# It supports implicit and explicit type casting

In [33]:
## check data type of elements
b.dtype

dtype('<U11')

In [34]:
help(b.dtype)

Help on dtype[str_] object:

class dtype[str_](dtype)
 |  Method resolution order:
 |      dtype[str_]
 |      dtype
 |      builtins.object
 |  
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from numpy._DTypeMeta
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from dtype:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __len__(self, /)
 |      Return len(self).
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __mul__(self, value, /)
 |      Return self*value.
 

In [ ]:
##  explicit conversion of data

In [35]:
b.dtype

dtype('<U11')

In [36]:
b.astype('float')

array([10., 20.])

In [37]:
c= b.astype('float')

In [38]:
c

array([10., 20.])

In [39]:
c.dtype

dtype('float64')

In [40]:
c.__sizeof__()

120

In [41]:
c.astype('int32')

array([10, 20])

In [42]:
d=c.astype('int32')

In [43]:
d

array([10, 20])

In [44]:
d.dtype

dtype('int32')

In [46]:
d.__sizeof__()

112

In [5]:
import numpy as np
np.array([10,5.6,25])

array([10. ,  5.6, 25. ])

In [6]:
d = np.array([10,5.6,25])
d

array([10. ,  5.6, 25. ])

In [7]:
d.dtype

dtype('float64')

In [8]:
d.astype('int')

array([10,  5, 25])

In [9]:
import numpy as np
f = np.array([10,'B',2.5])
f

array(['10', 'B', '2.5'], dtype='<U32')

In [10]:
f.dtype

dtype('<U32')

In [11]:
f.astype('int')

ValueError: invalid literal for int() with base 10: 'B'

In [12]:
t = np.array([12,34.5,(5+6j)])
t

array([12. +0.j, 34.5+0.j,  5. +6.j])

In [13]:
t.dtype

dtype('complex128')

In [14]:
t.astype('int')

C:\Users\Prerana\AppData\Local\Temp/ipykernel_2616/206733390.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  t.astype('int')


array([12, 34,  5])

In [15]:
t.astype('float')

C:\Users\Prerana\AppData\Local\Temp/ipykernel_2616/3143147714.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  t.astype('float')


array([12. , 34.5,  5. ])

In [16]:
t.astype('str')

array(['(12+0j)', '(34.5+0j)', '(5+6j)'], dtype='<U64')

# ##priority sequence of coversion--int, float, complex, string

In [17]:
p = np.array([1,0,0,1])
p

array([1, 0, 0, 1])

In [18]:
#convert bool
p.astype('bool')

array([ True, False, False,  True])

In [21]:
s= np.array([5,0,8,1])
s

array([5, 0, 8, 1])

In [22]:
s.astype('bool')

array([ True, False,  True,  True])

In [23]:
np.array([1,23.6,'A',0]).astype('bool')

ValueError: invalid literal for int() with base 10: '23.6'

# false 0 None '' apart from these 4 things evrything is true in python

In [25]:
np.array([12.5,20.7,4.8]).astype('int')

array([12, 20,  4])

# Difference between list and numpy array??
# Difference between python array and numpy array??

In [26]:
# In list we can not apply formulas on every element
i.e.# add 10 to each element
[11.5,4.7,8.9]+10

SyntaxError: invalid syntax (Temp/ipykernel_2616/26859294.py, line 2)

In [27]:
np.array([11.5,4.7,8.9]) + 10

array([21.5, 14.7, 18.9])

In [28]:
[1,2] + [3,4]  ## list will do the concatenation

[1, 2, 3, 4]

In [29]:
np.array([1,2]) + np.array([3,4])  ##numpy do the addition

array([4, 6])

# Different ways to create numpy array


In [30]:
np.array([1,2])

array([1, 2])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [35]:
np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
np.arange(1,16,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15])

# create array with all zeros


In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
# create array of 3 rows and 4 columns==> 2d array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# 3d array==>(2,3,3)==> 2 blocks, 3 rows and 3 columns
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# create array with all 1's

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
## If we want create an array with own values
np.full(10,5)    #full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [44]:
# 2 X 2 array filled by 100
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

# Identity array

In [45]:
# Identity matrix==> in which diagonal elements are 1's
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.eye(4,4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(4,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [50]:
e = np.identity(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [51]:
# transpose array
# row becomes column and viceversa
e.transpose()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
e = np.array([[1,3,4],[5,7,9],[3,9,6]])
e

array([[1, 3, 4],
       [5, 7, 9],
       [3, 9, 6]])

In [53]:
e.transpose()

array([[1, 5, 3],
       [3, 7, 9],
       [4, 9, 6]])

In [54]:
e.T

array([[1, 5, 3],
       [3, 7, 9],
       [4, 9, 6]])

In [55]:
np.transpose(e)

array([[1, 5, 3],
       [3, 7, 9],
       [4, 9, 6]])

In [ ]:
## you have an array
e = array([[1, 5, 3],
       [3, 7, 9],
       [4, 9, 6]])
# we want to transpose this array using python

In [2]:
f = []
e = ([[1, 5, 3],
       [3, 7, 9],
       [4, 9, 6]])
# for i in range(len(e)):
#     f.append(row[i] for row in e)

In [7]:
e[2][0]

4