In [5]:
import numpy as np


In [6]:
np.array([1,23,56,45,89])

array([ 1, 23, 56, 45, 89])

In [9]:
a = np.array([1,23,56,45,89])

In [10]:
a.argmax()

4

In [11]:
a.argmin()

0

In [12]:
a.cumsum()

array([  1,  24,  80, 125, 214], dtype=int32)

In [16]:
np.array(1,20)

TypeError: Cannot interpret '20' as a data type

In [18]:
b = np.array([[1,2,3],[6,7,8]])

In [19]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [21]:
b.shape

(2, 3)

In [22]:
b.ndim

2

In [23]:
b.cumsum()

array([ 1,  3,  6, 12, 19, 27], dtype=int32)

In [24]:
b.argmax(axis=1)#means row operation

array([2, 2], dtype=int64)

In [25]:
b.argmax(axis=0)#means column 

array([1, 1, 1], dtype=int64)

In [26]:
a

array([ 1, 23, 56, 45, 89])

In [27]:
list(a)#we can convert 1d array to list as

[1, 23, 56, 45, 89]

In [28]:
list(b)#to convert 2d array use the provision is use tolist as below

[array([1, 2, 3]), array([6, 7, 8])]

In [29]:
b.tolist()

[[1, 2, 3], [6, 7, 8]]

In [30]:
type(a)    #data type of array is numpy.ndarray(numpy.n-dimensional array)

numpy.ndarray

In [ ]:
#create an array using built in functions

In [32]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.arange(1,20,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [34]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [35]:
np.arange(20,1,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [36]:
np.arange(1,0,-1)

array([1])

In [37]:
np.arange(0,-9,-1)

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8])